# Generated by Django 4.0.4 on 2022-12-10 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_Delivery_Time',
        ),
    ]
