# Generated by Django 4.0.4 on 2022-12-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_isSale',
            field=models.BooleanField(default='False'),
        ),
    ]
