# Generated by Django 4.0.4 on 2022-12-11 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_product_issale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_Ticker',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
